AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: stops ec2 nightly
Parameters:
  CodeS3Bucket:
    Description: S3 Bucket in which the artifacts are stored
    Type: String
    MinLength: 3
  CodeS3Key:
    Description: S3 Key for the lambda artifact
    Type: String
    MinLength: 3
Resources:
  TimeFunction:
    Type: AWS::Serverless::Function
    Properties:
      Role: arn:aws:iam::406187633378:role/lambda-role
      Handler: lambda.lambda_handler
      Runtime: python3.10
      CodeUri:
        Bucket: !Ref CodeS3Bucket
        Key: !Ref CodeS3Key
      
